import { IsString, Length, Matches } from 'class-validator';

/**
 * DTO for the POST /meetings/join endpoint.
 *
 * Accepts the meetingCode in the format generated by Meeting.create():
 * 9 lowercase letters/digits in 3 segments of 3, separated by dashes.
 * Example: "abc-def-ghi"
 */
export class JoinMeetingRequestDto {
  @IsString()
  @Length(11, 11, { message: 'Meeting code must be exactly 11 characters' })
  @Matches(/^[a-z0-9]{3}-[a-z0-9]{3}-[a-z0-9]{3}$/, {
    message: 'Meeting code must match format "xxx-xxx-xxx"',
  })
  meetingCode: string;
}
